# [project]
# name = "ds-template"
# version = "2022.0.0"
# requires-python = ">=3.10"

# description = "Template Project - Data Science"
# readme = "README.md"
# license = {file = "LICENSE"}

# authors = [
#   {name = "Anthony Caliani", email = "https://github.com/avcaliani"},
#   {name = "Altiéris Peixoto", email = "https://github.com/altierispeixoto"}
# ]

# classifiers = [
#     "Development Status :: 4 - Beta",
#     "Topic :: Utilities",
#     "Programming Language :: Python",
#     "Programming Language :: Python :: 3",
#     "Programming Language :: Python :: 3 :: Only",
#     "Environment :: Console",
#     "Intended Audience :: Developers",
#     "License :: OSI Approved :: MIT License",
#     "Operating System :: POSIX :: Linux",
#     "Operating System :: Unix",
#     "Operating System :: MacOS",
#     "Operating System :: Microsoft :: Windows"
# ]

# [project.urls]
# documentation = "https://pyscaffoldext-custom-extension.readthedocs.io/"
# source = "https://github.com/pyscaffold/pyscaffoldext-custom-extension/"


[build-system]
# AVOID CHANGING REQUIRES: IT WILL BE UPDATED BY PYSCAFFOLD!
requires = ["setuptools>=46.1.0", "setuptools_scm[toml]>=5", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# See configuration details in https://github.com/pypa/setuptools_scm
version_scheme = "no-guess-dev"
